### ISSUE TITLE
Error in build_metabolic_model:Model source option not found

### ISSUE THREAD

**Issue by gaze-abyss** [borenstein-lab/mimosa2#10]
Hello, thank you for sharing the software. I met the following problem when I was using it, but I don't know how to solve it. Do you have any good suggestions? Thank you again!

```
> mimosa_results = run_mimosa2("config_example3.txt", make_plots = T, save_plots = T)
Building community metabolic network model
Error in build_metabolic_model(species, config_table, degree_filt = 0,  : 
  Model source option not found
```

This is 'config_example3.txt' file:
```
file1   126_asv.txt
file2   127.txt
ref_choices "EMBL_GEMs genomes and models"
file1_type  "Sequence variants (ASVs)"
simThreshold    0.99
data_prefix   ./ASV_AGORA/data/
vsearch_path    /cluster/apps/vsearch/2.22.1/bin/vsearch
rank_based    T
metType "KEGG Compound IDs"
signifThreshold   1
```

**Comment by cnoecker** [comment]
Hello,
Thanks for your interest in using MIMOSA2! The model option needs to exactly match one of the options listed in the documentation (here https://borenstein-lab.github.io/MIMOSA2shiny/package.html#). Try changing that line to "RefSeq/EMBL_GEMs genomes and models". 
Hope that helps!

**Comment by gaze-abyss** [comment]
Thanks for your reply. I was actually unable to download the dataset using the download_reference_data() function because it kept breaking. I downloaded ASV_EMBL.tar.gz(http://elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/refData/ASV_EMBL.tar.gz) and extracted it. How do I get RefSeq/EMBL_GEMs genomes and models?

**Comment by gaze-abyss** [comment]
> 

Thanks for your reply. I was actually unable to download the dataset using the download_reference_data() function because it kept breaking. I downloaded ASV_EMBL.tar.gz(http://elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/refData/ASV_EMBL.tar.gz) and extracted it. How do I get RefSeq/EMBL_GEMs genomes and models?

**Comment by cnoecker** [comment]
If you successfully downloaded the archive, then all you need to do is uncompress it and update your "data_prefix" in the configuration file to point to its location. Does that help?

**Comment by gaze-abyss** [comment]
> If you successfully downloaded the archive, then all you need to do is uncompress it and update your "data_prefix" in the configuration file to point to its location. Does that help?

Thank you for your help, but unfortunately I still can't run the software successfully, looking forward to the ShinyApp recovery!

**Comment by cnoecker** [comment]
Hello, very sorry for the delayed reply. The web application is now back online if you are still interested in using it for your analysis: elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/
