### ISSUE TITLE
can't get latest kegg files from kegg ftp

### ISSUE THREAD

**Issue by yayahoho1** [borenstein-lab/mimosa2#12]
hi, i can't get three latest kegg files(reaction_mapformula.lst, reaction, ko_reaction.list) needed from kegg ftp. Could you send old versions of these files or new to me? my eamil: liuyanggroups@outlook.com. Thanks!

**Comment by cnoecker** [comment]
Hello, I apologize for the slow reply. I will follow up by email.

**Comment by Gabderi** [comment]
Hello, could you please send the latest Kegg files reaction_mapformula.lst, reaction, ko_reaction.list) please.

My email is gabriel.deri3618@gmail.com

Thanks a lot!
