### ISSUE TITLE
Calculate CMP scores based on Metagenome: Total KO abundances only

### ISSUE THREAD

**Issue by drbmanna** [borenstein-lab/mimosa2#5]
Hi All,

I am trying to predict the community metabolic potential using MIMOSA2. 

1) I have the Metagenome: Total KO abundances.
2) I don't have any experimental metabolomics data.
3) I don't want the taxonomic contribution analysis; but only to perform the CMP-metabolite comparisons across the samples. 

Is there a way use the pipeline without metabolomics data input and stop at Step 2 as Fig. 1. (https://academic.oup.com/view-large/figure/337388629/btac003f1.tif) of the MIMOSA2 paper? 

Any help is appreciated. 

Thanks,
BM.

**Comment by cnoecker** [comment]
Hello, thanks for your question and I apologize for the delayed reply. You can find the answer to this question here: https://borenstein-lab.github.io/MIMOSA2shiny/faqs.html#cmpsAlone Alternatively, you may be able to obtain CMP scores using the web application by uploading a dummy metabolomics dataset with all the metabolite IDs of interest (and then only downloading the CMP score table from the generated results). 

Hope that helps!
