### ISSUE TITLE
Is Mimosa2 down?

### ISSUE THREAD

**Issue by nchorna812** [borenstein-lab/mimosa2#6]
Hello, trying to open http://elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/, - it is not loading

**Comment by Andrewab9** [comment]
Hi, same problem here

**Comment by cnoecker** [comment]
Hello, thanks for your interest in MIMOSA2! Yes, the web tool is currently down due to a larger issue with the server where it is hosted (beyond our control). Hopefully it will be back in a couple days.

**Comment by cnoecker** [comment]
Hello, very sorry for the delayed reply - there was actually a major server security issue and then some difficulties getting the environment restored correctly for MIMOSA2. Anyway, the web application is now back online if you are still interested in using it for your analysis: elbo-spice.cs.tau.ac.il/shiny/MIMOSA2shiny/

**Comment by nchorna812** [comment]
Hello Cecilia,
Thanks for a wonderful news!

Yes, we are very interested!

Nataliya
________________________________
