### ISSUE TITLE
Download database 

### ISSUE THREAD

**Issue by liaochenlanruo** [borenstein-lab/mimosa2#8]
Hi,
The link for database has lost, is there another way to dowload them? thanks!

**Comment by cnoecker** [comment]
Hi,
Thanks for your interest in MIMOSA2. We apologize for the ongoing server/download issues. You can now download selected datasets here: 
- AGORA dataset for use with ASV input data: https://drive.google.com/drive/folders/1HfcOIo1RsLdFgR_zgaNze8kIKpX-n8sd?usp=share_link
- EMBL_GEMS dataset for use with ASV input data: https://drive.google.com/drive/folders/1iCuiK1DOujAe9TFLW_SVlskqOJUU_quk?usp=share_link

Let me know if you have additional questions.
