### ISSUE TITLE
don't found kegg files from kegg ftp

### ISSUE THREAD

**Issue by nashanghenzan** [borenstein-lab/mimosa2#9]
hi, i don't found three kegg files(reaction_mapformula.lst, reaction, ko_reaction.list) needed from kegg ftp, where are them?

**Comment by cnoecker** [comment]
Hello,
Thanks for your interest in MIMOSA2! To my understanding, the "reaction_mapformula.lst" file and "reaction" file are located in the "ligand/reaction" folder in the KEGG FTP file system, and "ko_reaction.list" is in the "genes/ko" folder. Let me know if you are not able to locate them.

**Comment by nashanghenzan** [comment]
> Hello, Thanks for your interest in MIMOSA2! To my understanding, the "reaction_mapformula.lst" file and "reaction" file are located in the "ligand/reaction" folder in the KEGG FTP file system, and "ko_reaction.list" is in the "genes/ko" folder. Let me know if you are not able to locate them.

thanks for your reply, a few days ago, i aware of that i can't got these files from the free version of KEGG ftp. so i decide to wait for the web application of mimosa2

**Comment by cnoecker** [comment]
Ah, I see. If you provide your email address, I can send you old versions of these files from the last year they were freely available (2010-2011) - I believe they are about 80% complete. Otherwise, I am hopeful that our server issues will be resolved soon. Thank you.

**Comment by nashanghenzan** [comment]
> Ah, I see. If you provide your email address, I can send you old versions of these files from the last year they were freely available (2010-2011) - I believe they are about 80% complete. Otherwise, I am hopeful that our server issues will be resolved soon. Thank you.

thank you very much, my email: 913983298@qq.com

**Comment by cnoecker** [comment]
Sent!

**Comment by natalie-melendez** [comment]
Hi @cnoecker! I am also unable to acquire the Kegg files. Could you send them to me too at natalie.melendez2@upr.edu?

**Comment by cnoecker** [comment]
Yes, I will follow up by email. Thanks!

**Comment by laugior** [comment]
Hello @cnoecker. I would appreciate it if you could send the files to laureano.giordano[at]iucbc.edu.ar.
Thank you very much!

**Comment by nashanghenzan** [comment]
---Original---
From: ***@***.***&gt;
Date: Thu, Apr 17, 2025 01:10 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [borenstein-lab/mimosa2] don't found kegg files from kegg ftp(Issue #9)


   
Hello @cnoecker. I would appreciate it if you could send the files to laureano.giordano[at]iucbc.edu.ar.
 Thank you very much!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
  Tiltedkid left a comment (borenstein-lab/mimosa2#9)
 
Hello @cnoecker. I would appreciate it if you could send the files to laureano.giordano[at]iucbc.edu.ar.
 Thank you very much!
